name: Docker Image from master

on:
  push:
    branches:
      - master

jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@master
    - name: Build and Publish FRR releases for FRR and Debian
      uses: metal-stack/action-docker-make@master
      with:
        username: metalstackci
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        args: --no-lint --file docker-make.debian.yaml
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@master
    - name: Build and Publish FRR releases for FRR and Ubuntu
      uses: metal-stack/action-docker-make@master
      with:
        username: metalstackci
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        args: --no-lint --file docker-make.ubuntu.yaml
