name: Docker Image from master

on:
  pull_request:
    branches:
      - master

jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build FRR releases for Debian
      uses: metal-stack/action-docker-make@master
      with:
        username: metalstackci
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        args: --no-lint --no-push --file docker-make.debian.yaml
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build FRR releases for Ubuntu
      uses: metal-stack/action-docker-make@master
      with:
        username: metalstackci
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        args: --no-lint --no-push --file docker-make.ubuntu.yaml
